"""Redefined User

Revision ID: a76c31446a48
Revises: 4f75d4ec9f16
Create Date: 2025-03-09 11:07:07.530015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76c31446a48'
down_revision = '4f75d4ec9f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('salt',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('salt',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###
