volumes:
  db-data:

services:
  db:
    volumes:
      - db-data:/var/lib/mysql

  proxy:
    ports:
      - 80:80
      - 8080:8080
  
  backend:
    build:
      args:
        - FLASK_ENV=development
        - FLASK_DEBUG=1
    # Development code sync on modification. Run docker-compose command with --watch argument
    develop:
      watch:
        - action: sync
          path: ./flaskr/app
          target: /code/app