services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060

  backend:
    build:
      context: flaskr
      target: builder
    restart: always
    secrets:
      - db-password
    environment:
      - DATABASE_PASSWORD_FILE=/run/secrets/db-password
    # ports:
    #   - 8000:8000
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./flaskr/app
          target: /code/app
    expose:
      - 8000

  proxy:
    build: nginx
    restart: always
    ports:
      - 80:80
      - 8080:8080
    depends_on: 
      - backend
    networks:
      - frontnet

  phpmyadmin:
    image: phpmyadmin
    restart: always
    secrets:
      - db-password
    # ports:
    #   - 9080:80
    networks:
      - backnet
      - frontnet
    environment:
      # MYSQL_ROOT_PASSWORD: example
      # PMA_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_USER: pma_user
      MYSQL_PASSWORD: pma_pw
      PMA_HOST: db
    expose:
      - 80

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet:
